### PR TITLE
Update to cmdliner.1.1.0

### PR DESCRIPTION
**Pull request by MisterDA**
- update to cmdliner.1.1.0 ;
- ocaml-ci needs opam pin-depends to refer to a specific commit; refer to latest clecat/dream.
- [x] Dream is missing an opam dependency on `multipart_form-lwt` ;
- pin-depends on irmin, index, ocaml-git, hxd latest releases plus cmdliner.1.1.0 patches that I'm maintaining.

### CODE REVIEW

**Comment by clecat** [comment]
Thanks a lot for your work
A recent modification to `multipart_form` has indeed broken `dream`, I'll fix that and we should be able to merge your code

**Comment by MisterDA** [comment]
I'm somewhat annoyed to have all these pin-depends TBH, so if you want to delay the merge until all the associated PRs have been merged, I'd understand.

**Comment by clecat** [comment]
I was a bit annoyed bit them too, but because it might take some time before we can get rid of them, we will simply merge it and I will make sure to keep an issue about them so we dont forget to remove them in the near future : )

**Comment by clecat** [comment]
This should be ready for a merge, thank you for your work !

**Pull request merged**
